package com.common.OpenDriveAPI;

public class ODCloseFileUploadResponseInfo {

    public String FileId;
    public String Name;
    public String GroupID;
    public String Extension;
    public String Size;
    public String Views;
    public String Version;
    public String Downloads;
    public String DateTrashed;
    public String DateModified;
    public boolean OwnerSuspendet;
    public String AccType;
    public String FileHash;
    public String Link;
    public String DownloadLink;
    public String StreamingLink;
    public String OwnerName;
    public int upload_speed_limit;
    public int download_speed_limit;
    public int BWExceeded;
    public String ThumbLink;
    public String Encrypted;
    public String Password;
    public String OwnerLevel;
    public String EditOnline;
    public String ID;
    public String FolderID;
    public String Description;
    public String IsArchive;
    public String Category;
    public String Date;
    public String DateUploaded;
    public String DateAccessed;
    public String DirectLinkPublic;
    public String EmbedLink;
    public int AccessDisabled;
    public String Type;
    public String DestURL;
    public String Owner;
    public String AccessUser;
    public int DirUpdateTime;
    public String FileName;
    public String FileDate;
    public String FileDescription;
    public String FileDestUrl;
    public String FileKey;
    public String FilePrice;
    public String FileVersion;
    public String FileIp;
    public String FileIsPublic;
    public String DateTime;
}
